return {
	"ibhagwan/fzf-lua",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	config = function()
		local actions = require("fzf-lua").actions
		require("fzf-lua").setup({
			defaults = {
				hls = {
					file_part = "Directory",
				},
				fzf_colors = true,
				formatter = { "path.filename_first", 2 },
				file_icons = true,
				winopts = {
					width = 0.9,
					height = 0.85,
					preview = {
						vertical = "down:65%",
						hidden = false,
						layout = "horizontal",
						delay = 5,
						winopts = { number = false },
					},
				},
			},
			keymap = {
				builtin = {
					true,
					["<Esc>"] = "hide",
				},
				fzf = {
					true,
					["ctrl-q"] = "select-all+accept",
				},
			},
			fzf_opts = {
				["--margin"] = "0,0",
				["--layout"] = "reverse",
				["--exact"] = true,
				["--cycle"] = true,
			},
			lsp = {
				async_or_timeout = true,
			},
			oldfiles = {
				cwd_only = true,
				stat_file = true,
			},
			files = {
				fd_opts = table.concat({
					"--color=never ",
					"--hidden ",
					"--type f ",
					"--type l ",
					"-E '.git' ",
					"-E 'dev/' ",
					"-E 'dev/**' ",
					"-E 'vendor/**/tests/' ",
					"-E 'vendor/**/Test/' ",
					"-E 'vendor/composer/' ",
					"-E 'sync/' ",
					"-E 'lib/' ",
					"-E '.idea/' ",
					"-E 'setup/' ",
					"-E '.wexo/app/' ",
					"-E '.wexo/**/*.sql' ",
					"-E '.wexo/restore/' ",
					"-E '.wexo/.local/' ",
					"-E 'generated/' ",
					"-E 'pub/' ",
					"-E 'var/' ",
					"-E 'logs/' ",
					"-E 'CHANGELOG.md' ",
					"-E 'node_modules/' ",
					"-E 'dist/' ",
					"-E 'public/' ",
					"-E 'yarn.lock' ",
					"-E 'composer.lock' ",
				}),
				fzf_opts = {
					["--history"] = vim.fn.stdpath("data") .. "/fzf-lua-files-history",
				},
			},
			buffers = {
				sort_lastused = true,
				cwd_only = true,
				fzf_opts = {
					["--with-nth"] = "3..",
				},
			},
			grep = {
				fzf_opts = {
					["--history"] = vim.fn.stdpath("data") .. "/fzf-lua-grep-history",
				},
				rg_opts = table.concat({
					"-uu ",
					"--hidden ",
					"--column ",
					"--line-number ",
					"--no-heading ",
					"--color=always ",
					"--smart-case ",
					"--max-columns=4096 ",
					"-F ",
					"-g !dev/ ",
					"-g !dev/** ",
					"-g !vendor/**/tests/ ",
					"-g !vendor/**/Test/ ",
					"-g !vendor/composer/ ",
					"-g !sync/ ",
					"-g !lib/ ",
					"-g !.idea/ ",
					"-g !setup/ ",
					"-g !.wexo/app/ ",
					"-g !.wexo/**/*.sql ",
					"-g !.wexo/restore/ ",
					"-g !.wexo/.local/ ",
					"-g !generated/ ",
					"-g !pub/ ",
					"-g !var/ ",
					"-g !logs/ ",
					"-g !CHANGELOG.md ",
					"-g !node_modules/ ",
					"-g !dist/ ",
					"-g !.git/ ",
					"-g !public/ ",
					"-g !yarn.lock ",
					"-g !composer.lock ",
				}),
			},
			actions = {
				files = {
					true,
					["ctrl-g"] = actions.toggle_ignore,
				},
			},
		})
	end,
}
